services:
  db:
    image: postgres:16
    container_name: alliance-db
    environment:
      POSTGRES_DB: Alliance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alliance
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - alliance-net
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  # backend:
  # frontend:
  # nginx:
  
networks:
  alliance-net:

volumes:
  pgdata:
